[2017-05-02 03:10:16 +0000] [30810] [INFO] Starting gunicorn 19.7.1
[2017-05-02 03:10:16 +0000] [30810] [INFO] Listening at: http://127.0.0.1:8000 (30810)
[2017-05-02 03:10:16 +0000] [30810] [INFO] Using worker: sync
[2017-05-02 03:10:16 +0000] [30810] [INFO] Server is ready. Spawning workers
[2017-05-02 03:10:16 +0000] [30815] [INFO] Booting worker with pid: 30815
[2017-05-02 03:10:16 +0000] [30815] [INFO] Worker spawned (pid: 30815)
[2017-05-02 03:13:00 +0000] [30815] [INFO] worker received INT or QUIT signal
[2017-05-02 03:13:00 +0000] [30810] [INFO] Handling signal: int
[2017-05-02 03:13:00 +0000] [30815] [INFO] worker received INT or QUIT signal
[2017-05-02 03:13:00 +0000] [30815] [INFO] Worker exiting (pid: 30815)
[2017-05-02 03:13:00 +0000] [30810] [INFO] Shutting down: Master
[2017-05-02 03:13:54 +0000] [30831] [INFO] Starting gunicorn 19.7.1
[2017-05-02 03:13:54 +0000] [30831] [INFO] Listening at: http://127.0.0.1:8000 (30831)
[2017-05-02 03:13:54 +0000] [30831] [INFO] Using worker: sync
[2017-05-02 03:13:54 +0000] [30831] [INFO] Server is ready. Spawning workers
[2017-05-02 03:13:54 +0000] [30836] [INFO] Booting worker with pid: 30836
[2017-05-02 03:13:54 +0000] [30836] [INFO] Worker spawned (pid: 30836)
[2017-05-02 03:13:54 +0000] [30836] [ERROR] Exception in worker process
Traceback (most recent call last):
  File "/home/kluthr/src/Jambot/env/local/lib/python2.7/site-packages/gunicorn/arbiter.py", line 578, in spawn_worker
    worker.init_process()
  File "/home/kluthr/src/Jambot/env/local/lib/python2.7/site-packages/gunicorn/workers/base.py", line 126, in init_process
    self.load_wsgi()
  File "/home/kluthr/src/Jambot/env/local/lib/python2.7/site-packages/gunicorn/workers/base.py", line 135, in load_wsgi
    self.wsgi = self.app.wsgi()
  File "/home/kluthr/src/Jambot/env/local/lib/python2.7/site-packages/gunicorn/app/base.py", line 67, in wsgi
    self.callable = self.load()
  File "/home/kluthr/src/Jambot/env/local/lib/python2.7/site-packages/gunicorn/app/wsgiapp.py", line 65, in load
    return self.load_wsgiapp()
  File "/home/kluthr/src/Jambot/env/local/lib/python2.7/site-packages/gunicorn/app/wsgiapp.py", line 52, in load_wsgiapp
    return util.import_app(self.app_uri)
  File "/home/kluthr/src/Jambot/env/local/lib/python2.7/site-packages/gunicorn/util.py", line 352, in import_app
    __import__(module)
  File "/home/kluthr/src/Jambot/WhatToMusic/jambot/app.py", line 31, in <module>
    @app.route('/')
AttributeError: 'ReverseProxied' object has no attribute 'route'
[2017-05-02 03:13:54 +0000] [30836] [INFO] Worker exiting (pid: 30836)
[2017-05-02 03:13:54 +0000] [30831] [INFO] Shutting down: Master
[2017-05-02 03:13:54 +0000] [30831] [INFO] Reason: Worker failed to boot.
